# fly.toml app configuration file generated for mermaid-for-slack on 2023-08-28T00:25:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mermaid-for-slack"
primary_region = "ams"

[build]

[deploy]
  strategy = "rolling"

[[http_service.checks]]
  grace_period = "10s"
  interval = "12h"
  method = "GET"
  timeout = "5s"
  path = "/"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/public"
